.include "asm_setup.S"

.global ItemChances

# Regular Items
ItemChances:

# Green Shell
.byte 34,67

# Red Shell
.byte 34,67

# Banana
.byte 34,67

# FIB
.byte 34,67

# Mushroom
.byte 34,67

# Salty Six (TRIPLE ONLY)
.byte 0,0

# Bomb
.byte 95,99

# Blue Shell
.byte 95,99

# Shock
.byte 95,99

# Star
.byte 85,95

# Golden
.byte 95,99

# Mega
.byte 85,95

# Feather
.byte 85,95

# POW
.byte 95,99

# TC (SINGLE ONLY)
.byte -1,-1

# Bullet Bill
.byte 95,99

# Triple Banana (UNUSED)
.byte -1,-1

# Triple Green (UNUSED)
.byte -1,-1

# Triple Red (UNUSED)
.byte -1,-1

# Newbie Helper Items

# Green Shell (UNUSED)
.byte -1,-1

# Red Shell (UNUSED)
.byte -1,-1

# Banana (UNUSED)
.byte -1,-1

# FIB (UNUSED)
.byte -1,-1

# Mushroom
.byte 34,67

# Salty Six (TRIPLE ONLY)
.byte 0,0

# Bomb (UNUSED)
.byte -1,-1

# Blue Shell
.byte 85,95

# Shock
.byte 95,99

# Star
.byte 34,67

# Golden
.byte 85,95

# Mega
.byte 34,67

# Feather (UNUSED)
.byte -1,-1

# POW
.byte 95,99

# TC (SINGLE ONLY)
.byte -1,-1

# Bullet Bill
.byte 95,99

# Triple Banana (UNUSED)
.byte -1,-1

# Triple Green (UNUSED)
.byte -1,-1

# Triple Red (UNUSED)
.byte -1,-1
.align 2
